name: mhft
error_table: PerAtomRMSEstressvirials
compute_stress: true
energy_key: energy
forces_key: forces
stress_key: stress
foundation_model: /path/to/mace-mpa-0-medium.model
train_file: /path/to/train_set.extxyz
test_file: /path/to/test_set.extxyz
valid_file: /path/to/validation_set.extxyz
pt_train_file: mp
E0s: /path/to/E0s.json
lr: 0.0001
force_mh_ft_lr: true
num_samples_pt: 50000
forces_weight: 10
energy_weight: 10
stress_weight: 1
ema: true
ema_decay: 0.99999
batch_size: 8
valid_batch_size: 8
max_num_epochs: 20
device: cuda
enable_cueq: true
seed: 123
multiheads_finetuning: true
