name: nft
error_table: PerAtomRMSE
compute_stress: true
energy_key: energy
forces_key: forces
stress_key: stress
foundation_model: /path/to/mace-mpa-0-medium.model
train_file: /path/to/train_set.extxyz
test_file: /path/to/test.extxyz
valid_file: /path/to/validation_set.extxyz
E0s: /path/to/E0s.json
lr: 0.0005
forces_weight: 10
energy_weight: 10
stress_weight: 1
ema: true
ema_decay: 0.99
batch_size: 2
valid_batch_size: 2
max_num_epochs: 500
device: cuda
enable_cueq: true
seed: 123
multiheads_finetuning: false
