name: scratch
error_table: PerAtomRMSE
compute_stress: true
energy_key: energy
forces_key: forces
stress_key: stress
train_file: /path/to/train_set.extxyz
test_file: /path/to/test_set.extxyz
valid_file: /path/to/validation_set.extxyz
E0s: /path/to/E0s.json
model: MACE
num_channels: 128
max_L: 1
r_max: 6.0
batch_size: 4
valid_batch_size: 4
max_num_epochs: 500
swa: true
start_swa: 400
device: cuda
enable_cueq: true
seed: 123
